docker run -it -d \
  --label traefik.http.routers.flymaxmicrofinance.rule=Host\(\`flymaxmicrofinance.online\`\) \
  --label traefik.http.routers.flymaxmicrofinance.tls.certresolver=lets-encrypt \
  --label traefik.http.routers.flymaxmicrofinance.tls=true \
  --label traefik.http.routers.flymaxmicrofinance.service=flymaxmicrofinance-credit-http \
  --label traefik.http.services.flymaxmicrofinance-credit-http.loadbalancer.server.port=80 \
  --name flymaxmicrofinance \
  --network web \
  --restart always \
  --expose 80 \
mikoposoft/nackcredit:latest








docker run -it -d \
  --label traefik.http.routers.dnpmicrofinance.rule=Host\(\`dnpmicrofinance.com\`\) \
  --label traefik.http.routers.dnpmicrofinance.tls.certresolver=lets-encrypt \
  --label traefik.http.routers.dnpmicrofinance.tls=true \
  --label traefik.http.routers.dnpmicrofinance.service=dnpmicrofinance-credit-http \
  --label traefik.http.services.dnpmicrofinance-credit-http.loadbalancer.server.port=80 \
  --name dnpmicrofinance \
  --network web \
  --restart always \
  --expose 80 \
mikoposoft/dnpmicrofinance:26may




















