docker run -it -d \
  --label traefik.http.routers.farabethmicrocredit.rule=Host\(\`farabethmicrocredit.credit\`\) \
  --label traefik.http.routers.farabethmicrocredit.tls.certresolver=lets-encrypt \
  --label traefik.http.routers.farabethmicrocredit.tls=true \
  --label traefik.http.routers.farabethmicrocredit.service=farabethmicrocredit-credit-http \
  --label traefik.http.services.farabethmicrocredit-credit-http.loadbalancer.server.port=80 \
  --name farabethmicrocredit \
  --network web \
  --restart always \
  --expose 80 \
mikoposoft/farabat:latest



















