docker run -it -d \
  --label traefik.http.routers.flymaxmicrofinance.rule=Host\(\`flymaxmicrofinance.online\`\) \
  --label traefik.http.routers.flymaxmicrofinance.tls.certresolver=lets-encrypt \
  --label traefik.http.routers.flymaxmicrofinance.tls=true \
  --label traefik.http.routers.flymaxmicrofinance.service=flymaxmicrofinance-credit-http \
  --label traefik.http.services.flymaxmicrofinance-credit-http.loadbalancer.server.port=80 \
  --name flymaxmicrofinance \
  --network web \
  --restart always \
  --expose 80 \
mikoposoft/nackcredit:latest








docker run -it -d \
  --label traefik.http.routers.essamdigital.rule=Host\(\`essamdigital.co.tz\`\) \
  --label traefik.http.routers.essamdigital.tls.certresolver=lets-encrypt \
  --label traefik.http.routers.essamdigital.tls=true \
  --label traefik.http.routers.essamdigital.service=essamdigital-credit-http \
  --label traefik.http.services.essamdigital-credit-http.loadbalancer.server.port=80 \
  --name essamdigital \
  --network web \
  --restart always \
  --expose 80 \
mikoposoft/essam:19_july_2026




















